### ISSUE TITLE
Some Links in Landing Page do not Work

### ISSUE THREAD

**Issue by JohnOjo** [BinaryNinjaz/COS301-Capstone#29]

**Comment by Letanyan** [comment]
Which ones?

**Comment by JohnOjo** [comment]
The Git and Slack ones as far as I know. They just go to a blank page when I click on them.

**Comment by Letanyan** [comment]
They work for me. The BinaryNinjaz ones at the bottom right?

**Comment by JohnOjo** [comment]
Yes, the ones at the bottom of the landing page.

**Comment by Letanyan** [comment]
Clicking normally seems to be not allowed for security reasons on the cs site. However, open it in a new tab works fine. I'm not sure how we would fix it to work with just a click.

**Comment by Letanyan** [comment]
I made the all the links open in a new tab by default
